services:
  ordering.consumer:
    container_name: ordering.consumer
    image: ordering.consumer
    build:
      context: .
      dockerfile: src/Ordering.Consumer/Dockerfile
    depends_on:
      - ordering.db
      - ordering.rabbitmq
        
  ordering.producer:
    container_name: ordering.producer
    image: ordering.producer
    build:
      context: .
      dockerfile: src/Ordering.Producer/Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5268:8080
    depends_on:
      - ordering.rabbitmq
      
  ordering.db:
    container_name: ordering.db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    depends_on:
      - ordering.rabbitmq
      
  ordering.rabbitmq:
    container_name: ordering.rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=ordering
      - RABBITMQ_DEFAULT_PASS=ordering
    ports:
      - 5672:5672
      - 15672:15672
