services:
  ordering.api:
    container_name: ordering.api
    image: ordering.api
    build:
      context: .
      dockerfile: src/Ordering.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8081
    ports:
      - 5260:8081
    depends_on:
      - ordering.seq
      - ordering.db
  
  ordering.consumer:
    container_name: ordering.consumer
    image: ordering.consumer
    build:
      context: .
      dockerfile: src/Ordering.Consumer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__Host: ordering.rabbitmq
    depends_on:
      - ordering.db
      - ordering.rabbitmq
  
  ordering.producer:
    container_name: ordering.producer
    image: ordering.producer
    build:
      context: .
      dockerfile: src/Ordering.Producer/Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__Host: ordering.rabbitmq
    ports:
      - 5261:8080
    depends_on:
      - ordering.rabbitmq
  
  ordering.db:
    container_name: ordering.db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
  
  ordering.rabbitmq:
    container_name: ordering.rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=ordering
      - RABBITMQ_DEFAULT_PASS=ordering
    ports:
      - 5672:5672
      - 5262:15672
        
  ordering.seq:
    container_name: ordering.seq
    image: datalust/seq:latest
    ports:
      - 5341:5341
      - 5263:80
    environment:
      ACCEPT_EULA: Y
