# This is a generated file. Not intended for manual editing.
services:
  ordering.consumer:
    build:
      context: "C:\\Users\\gsousa\\RiderProjects\\edital-btg-pactual"
      dockerfile: "src/Ordering.Consumer/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ordering.consumer:dev"
    ports:
    - "127.0.0.1:57042:57000"
    - "127.0.0.1:57242:57200"
    - "127.0.0.1:57442:57400"
    volumes:
    - "C:\\Users\\gsousa\\RiderProjects\\edital-btg-pactual\\src\\Ordering.Consumer:/app:rw"
    - "C:\\Users\\gsousa\\RiderProjects\\edital-btg-pactual:/src:rw"
    - "C:\\Users\\gsousa\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\gsousa\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.6\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.3\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\gsousa\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_06_20_46_46:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  ordering.producer:
    build:
      context: "C:\\Users\\gsousa\\RiderProjects\\edital-btg-pactual"
      dockerfile: "src/Ordering.Producer/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ordering.producer:dev"
    ports:
    - "127.0.0.1:57043:57000"
    - "127.0.0.1:57243:57200"
    - "127.0.0.1:57443:57400"
    volumes:
    - "C:\\Users\\gsousa\\RiderProjects\\edital-btg-pactual\\src\\Ordering.Producer:/app:rw"
    - "C:\\Users\\gsousa\\RiderProjects\\edital-btg-pactual:/src:rw"
    - "C:\\Users\\gsousa\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\gsousa\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.6\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.3\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\gsousa\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_06_20_46_46:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
